apiVersion: v1
kind: Template
labels:
  template: f8a-graph-cve-sync
metadata:
  name: f8a-graph-cve-sync
  annotations:
    description: f8a-graph-cve-sync
objects:
- apiVersion:  batch/v1beta1
  kind: CronJob
  metadata:
    name: f8a-graph-cve-sync
    annotations:
      description: f8a-graph-cve-sync
  spec:
    successfulJobsHistoryLimit: 4
    failedJobsHistoryLimit: 1
    concurrencyPolicy: "Forbid"
    schedule: "${CRON_SCHEDULE}"
    jobTemplate:
      spec:
        template:
          spec:
            restartPolicy: Never
            containers:
            - name: f8a-graph-cve-sync
              image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
              env:
                - name: SYNC_MODE
                  value: "${SYNC_MODE}"
                - name: DRY_RUN
                  value: "${DRY_RUN}"
                - name: REPORT_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: developer-analytics-audit-report-s3
                      key: bucket
                - name: AWS_S3_SECRET_ACCESS_KEY_REPORT_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: developer-analytics-audit-report-s3
                      key: aws_secret_access_key
                - name: AWS_S3_ACCESS_KEY_ID_REPORT_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: developer-analytics-audit-report-s3
                      key: aws_access_key_id
                - name: AWS_S3_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: bayesian-config
                      key: aws-default-region
              resources:
                requests:
                  memory: ${MEMORY_REQUEST}
                  cpu: ${CPU_REQUEST}
                limits:
                  memory: ${MEMORY_LIMIT}
                  cpu: ${CPU_LIMIT}
parameters:
- description: Docker registry
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "quay.io"

- description: Docker image
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "openshiftio/fabric8-analytics-graph-cve-sync"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"

- description: Sync mode
  displayName: Sync mode
  required: true
  name: SYNC_MODE
  value: "diff"

- description: Dry run
  displayName: Dry run
  required: true
  name: DRY_RUN
  value: "false"

- description: Schedule
  displayName: Schedule
  required: true
  name: CRON_SCHEDULE
  value: "0 */6 * * *"

- description: CPU request
  displayName: CPU request
  required: true
  name: CPU_REQUEST
  value: "250m"

- description: CPU limit
  displayName: CPU limit
  required: true
  name: CPU_LIMIT
  value: "500m"

- description: Memory request
  displayName: Memory request
  required: true
  name: MEMORY_REQUEST
  value: "256Mi"

- description: Memory limit
  displayName: Memory limit
  required: true
  name: MEMORY_LIMIT
  value: "1024Mi"
